name: CI

env:
  go-version: "1.19"

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  quicktests:
    env:
      execute: "true"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        if: env.execute == 'true'
        uses: actions/checkout@v3
      - name: set up go
        if: env.execute == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
      - name: fmt, tidy, lint
        if: env.execute == 'true'
        run: |
          make install
          make test-tidy
          make test-fmt
      - name: Mark the job as succeeded
        if: env.execute == 'false'
        run: exit 0

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
      - name: setup env
        run: make install
      - name: lint
        run: make lint-github-action

  unittests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    needs:
      - quicktests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
      - name: unit tests
        run: make test-all
